import OpenAI from 'openai';

export async function judge(review1: any[], review2: any[], debug: boolean): Promise<string> {
  const client = new OpenAI({
    baseURL: 'https://openrouter.ai/api/v1',
    apiKey: process.env.OPENROUTER_API_KEY,
  });

  if (debug) console.log(`[DEBUG] Judge: Combining ${review1.length + review2.length} findings for report generation.`);

  const combinedFindings = [...review1, ...review2];

  const template = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Code Review Report</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: -apple-system, sans-serif; line-height: 1.6; background: #f8f9fa; padding: 24px; }
        .container { max-width: 960px; margin: 0 auto; background: white; border-radius: 8px; box-shadow: 0 2px 8px rgba(0,0,0,0.1); overflow: hidden; }
        header { background: #1a1a2e; color: white; padding: 24px 32px; }
        .stat { text-align: center; padding: 16px; background: #fff; border: 1px solid #eee; border-radius: 6px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px 32px; text-align: left; border-bottom: 1px solid #eee; }
        .badge { padding: 4px 8px; border-radius: 4px; font-size: 0.8rem; font-weight: 600; }
        .badge-warn { background: #fff3cd; color: #856404; }
        .badge-info { background: #d1ecf1; color: #0c5460; }
        .footer { padding: 24px 32px; font-size: 0.8rem; color: #666; background: #fafafa; }
    </style>
</head>
<body>
    <div class="container">
        <header><h1>Code Review Report</h1></header>
        <table>
            <thead><tr><th>Line</th><th>Severity</th><th>Category</th><th>Description</th></tr></thead>
            <tbody>
                <!-- LLM WILL FILL ROWS HERE -->
            </tbody>
        </table>
        <div class="footer">Generated by Lead Developer Review Synthesis</div>
    </div>
</body>
</html>`;

  const systemPrompt = `
You are a Lead Developer. 
Your task is to generate a complete, valid, and styled HTML document.

You are a Lead Developer. 
1. De-duplicate findings and remove false positives.
2. YOU MUST OUTPUT YOUR FINDINGS INTO THE EXACT HTML TEMPLATE PROVIDED BELOW.
3. Do not change the CSS classes or the overall structure.
4. Only output the final HTML.
TEMPLATE:
${template}
`;

  const completion = await client.chat.completions.create({
    model: 'nvidia/nemotron-3-ultra-550b-a55b:free',
    messages: [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: `Template: ${template}\n\nFindings: ${JSON.stringify(combinedFindings)}` }
    ]
  });

  if (debug) console.log(`[DEBUG] Judge: Report synthesis complete.`);

  const rawHtml = completion.choices[0].message.content || '<h1>Report Error</h1>';
  return rawHtml.replace(/```html/g, '').replace(/```/g, '').trim();
}